### ISSUE TITLE
Remove stroke from Light Control Panel

### ISSUE THREAD

**Issue by DianaTavares** [phetsims/models-of-the-hydrogen-atom#62]
From September 9 desing meeting: 
Delete the line around the panel. Stroke weight zero.

![image](https://github.com/user-attachments/assets/cc18287a-4ddb-4065-9b6d-4b0547ff25f4)

**Comment by pixelzoom** [comment]
I was not present at the Sept 9 design meeting, and I'd like to discuss this change request, because I had some good reasons for adding the panel stroke.  The purpose of the stroke is to visually group the controls that are related to the light.  I felt that became necessary when (1) we added a big vertical space between the radio buttons and the wavelength slider, to show when the slider is set to an absorption wavelength, and (2) we decided that the "Absorption/Emission" checkbox was not part of the light controls, because it's relevant to the light + Spectrometer + Energy Levels diagram.  Removing the stroke makes it unclear what controls are related to the light. And I think it makes the vertical spacing look bad.   

Screenshots with and without panel stroke are shown below.

<img width="1034" alt="screenshot_3492" src="https://github.com/user-attachments/assets/2ba5dcf3-fcf8-42c0-b7fc-5348536f6fa2">
<img width="1040" alt="screenshot_3493" src="https://github.com/user-attachments/assets/abf11e62-a180-4de1-b8bd-248faa0dcf57">

**Comment by DianaTavares** [comment]
For me, it was strange to see an empty panel when the light is in White:
![image](https://github.com/user-attachments/assets/f0f0a2a3-1f42-454f-982f-ca79c523a4de)

But I see your point and yes, it is better to have the strokes. It is stranger not have them!
