### ISSUE TITLE
Consider adding "classical" or "quantum" to radiobutton name instead on in help text.

### ISSUE THREAD

**Issue by terracoda** [phetsims/models-of-the-hydrogen-atom#84]
In #78, we decided to not add classical/quantum to the Model radio group help text. 
I support that decision. Designers felt comfortable with referring to the classical-quantum continuum in the scene summary.

Then, while testing the AB Switch, I realized that “classical” or “quantum” could be added as part of the accessible name for each radio button. We did this on MAL when we wanted to call out the geometries of the molecule images visually present next to each molecule name in the radio group.

Advantages for doing this, the names and help text can stay consistent across screens, and the scene summary can be shortened., and the classical/quantum information is included in an apt and timely way along side the name for the radio button, like it is visually. The information is at the end of the name, so it can be skipped easily when pressing the Tab key or Down arrow.

Current Design is:

> **Atomic Model**
> Choose atomic model to explore.
> - Billiard Ball
> - Plum Pudding
> - Classical Solar System
> - Bohr
> - de Broglie
> - Schrödinger

I am suggesting:

**Atomic Model**
Choose atomic model to explore.
- Billard Ball, classical
- Plum Pudding, classical
- Solar System, classical
- Bohr, quantum
- de Brogli, quantum
- Scrödinger, quantum

Here's the example from Molecules and Light
**Molecules**
Choose molecule for observation window.
- Carbon Monoxide, CO, linear
- Nitrogen, N2, linear
- Oxygen, O2, linear
- Carbon Dioxide, CO2, linear
- Methane, CH4, tetrahedral
- Water, H2O, bent
- Nitrogen Dioxide, NO2, bent
- Ozone, O3, bent
![Screenshot 2024-11-12 at 16 24 07](https://github.com/user-attachments/assets/bcb6847e-41c5-4ccb-bcd2-234a74adaae1)

**Comment by terracoda** [comment]
@DianaTavares, @arouinfar, @Nancy-Salpepi, this doesn't have to be for this release. 

I just feel this option was not discussed and it feels like a cleaner and simpler description design to me.

**Comment by pixelzoom** [comment]
I'll defer to the designers.  But labeling these models as either classical or quantum is not pedagocially correct.  It's a continuum, not either/or.  Bohr was the first to use aspects of quantum mechanics, probably before it was even called that, but is still particle-based.  de Brogile started to add wave-like behavior.  It wasn't until Schrodinger that the model was "quantum" in the sense that we think of quantum; that is particle and wavefunction based.  Hence the reason why we have a "Quantum Numbers" info dialog for the Schrodinger.

**Comment by terracoda** [comment]
Ok, good to know! This naming suggestion won’t work then. I will close the issue.

It is a good option in other cases, like in Molecules and Light.

Closing.

**Comment by arouinfar** [comment]
I was typing up my response when @terracoda closed the issue, but I decided to post this anyway so it would be on the record.

---

Thanks for the suggestion @terracoda, but I don't think it's a good fit for MOTHA. @pixelzoom pointed out the issues with the classical/quantum distinction, but there are a few additional reasons.

Pedagogically, this isn't a parallel example to MAL. Understanding the molecular geometry is central to the learning goals. This is the reason why we display the molecules in the radio buttons, and it makes sense to convey that information in the accessible names. 

We do not display the continuum on the Energy Levels Screen, so adding 'quantum' to the end of the accessible names would be inconsistent with the visuals. Changing the accessible name of the radio button based on the screen is unreasonable, in my opinion.

Even if the 'classical' and 'quantum' distinctions were appropriate, it would pose issues for PhET-iO. 
* Clients may want to change the name of the models, eg. 'Plum Pudding' to 'Thomson'. The way things are now, changing the visuals in the sim automatically updates the accessible name. 
* `continuumBarNode` can be hidden, so clients would need to manually remove 'classical' and 'quantum' from each accessible name to keep the representation consistent. Because the accessible name is not the string key used in the visuals, clients would have to go digging to find it.
